sudo: required

language: c

service:
  - docker

addons:
  apt:
    packages:
    - autoconf
    - automake
    - check
    - docker-engine
    - gcc
    - gperf
    - help2man
    - libdbi-dev
    - libglib2.0-dev
    - libtool
    - unzip
    - wget

before_script:
  - wget https://github.com/naemon/naemon-core/archive/master.zip
  - unzip master.zip
  - pushd naemon-core-master && autoreconf --install --force && ./configure && make && sudo make install && popd
  - autoreconf --install --force

script:
  - docker ps && ./configure && make && make features/binlog.feature
