sudo: required

language: c

services:
  - docker

addons:
  apt:
    packages:
    - autoconf
    - automake
    - check
    - docker-engine
    - gcc
    - gperf
    - help2man
    - libdbi-dev
    - libglib2.0-dev
    - libtool
    - unzip
    - wget

before_script:
  - wget https://github.com/naemon/naemon-core/archive/master.zip
  - unzip master.zip
  - pushd naemon-core-master && autoreconf --install --force && ./configure && make && sudo make install && popd
  - autoreconf --install --force

script:
  - ./configure && make && time make -j int-test feature_tests="features/binlog.feature features/check_result_output.feature features/config_sync_poller.feature features/connection.feature features/execute_host_checks.feature features/hostgroup_split.feature features/ipc_nodeinfo_version.feature features/livestatus.feature features/peer_nodeinfo_version.feature features/report_data_host_active.feature features/report_data_service_active.feature features/retention_data_oconf_hash.feature"
  - time make int-test feature_tests="features/binlog.feature features/check_result_output.feature features/config_sync_poller.feature features/connection.feature features/execute_host_checks.feature features/hostgroup_split.feature features/ipc_nodeinfo_version.feature features/livestatus.feature features/peer_nodeinfo_version.feature features/report_data_host_active.feature features/report_data_service_active.feature features/retention_data_oconf_hash.feature"
